/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.tss.GestioneCalcio;

import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tss
 */
public class WinCalcio extends javax.swing.JFrame {

    static ArrayList<Squadra> listasquadre = new ArrayList<>();
    static ArrayList<Partita> listapartite = new ArrayList<>();
    static ArrayList<Classifica> listaClassifica = new ArrayList<>();

    /**
     * Creates new form WinCalcio
     */
    public WinCalcio() {
        initComponents();
        clear();
        carica();
        refreshLista();
        clearPartite();
        caricaPartite();
        refreshListaPartite();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListSquadre = new javax.swing.JList<>();
        lblSquadre = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSede = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        txSede = new javax.swing.JTextField();
        lblSquadra = new javax.swing.JLabel();
        btnNuovo = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblGiornata = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSquadra1 = new javax.swing.JLabel();
        lblSquadra2 = new javax.swing.JLabel();
        lblGol1 = new javax.swing.JLabel();
        lblGol2 = new javax.swing.JLabel();
        txSquadra1 = new javax.swing.JTextField();
        txGiornata = new javax.swing.JTextField();
        txSquadra2 = new javax.swing.JTextField();
        txGol1 = new javax.swing.JTextField();
        txGol2 = new javax.swing.JTextField();
        lblPartita = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstElencoPartite = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblClassifica = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstClassifica = new javax.swing.JList<>();
        btnNew = new javax.swing.JButton();
        btnClassifica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListSquadre);

        lblSquadre.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblSquadre.setText("Elenco Squadre");

        lblNome.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblNome.setText("Nome :");

        lblSede.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblSede.setText("Sede:");

        lblSquadra.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblSquadra.setText("Squadra");

        btnNuovo.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnNuovo.setText("Nuovo");
        btnNuovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuovoActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnUpdate.setText("Update");

        lblGiornata.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblGiornata.setText("Giornata:");

        lblSquadra1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblSquadra1.setText("Squadra1 :");

        lblSquadra2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblSquadra2.setText("Squadra2 :");

        lblGol1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblGol1.setText("Gol1");

        lblGol2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblGol2.setText("Gol2");

        lblPartita.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblPartita.setText("Partita");

        jScrollPane2.setViewportView(lstElencoPartite);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elenco Partite");

        lblClassifica.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblClassifica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClassifica.setText("Classifica");

        jScrollPane3.setViewportView(lstClassifica);

        btnNew.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnNew.setText("Nuovo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnClassifica.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnClassifica.setText("Classifica");
        btnClassifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSede, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSquadra, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txNome, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txSede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuovo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSquadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPartita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblGiornata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSquadra2)
                                .addComponent(lblSquadra1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addComponent(lblGol1)
                            .addComponent(lblGol2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txGol2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(txGol1)
                                    .addComponent(txGiornata)
                                    .addComponent(txSquadra1)
                                    .addComponent(txSquadra2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel2)
                                        .addGap(247, 247, 247))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(189, 189, 189)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                                .addComponent(btnClassifica)
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblClassifica, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSquadre, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(lblPartita))
                        .addComponent(lblSquadra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSede)
                            .addComponent(txSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addComponent(btnNuovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblClassifica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGiornata, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txGiornata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSquadra2)
                                    .addComponent(txSquadra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGol1)
                                    .addComponent(txGol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGol2)
                                    .addComponent(txGol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClassifica)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuovoActionPerformed

        String nome = txNome.getText();
        String sede = txSede.getText();
        Squadra squadra = new Squadra(nome, sede);
        boolean esiste = false;

        for (Squadra squadra1 : listasquadre) {
            if (squadra.equals(squadra1)) {
                esiste = true;
            }
        }

        if (esiste == false) {
            listasquadre.add(squadra);
            JOptionPane.showMessageDialog(null, "SQUADRA INSERITA CORRETTAMENTE!");
            clear();
            salvaSquadra();
        } else {
            JOptionPane.showMessageDialog(null, "NON È POSSIBILE INSERIRE UNA SQUADRA GIÀ PRESENTE!");

        }
        refreshLista();


    }//GEN-LAST:event_btnNuovoActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        int giornata = Integer.parseInt(txGiornata.getText());
        String squadra1 = txSquadra1.getText();
        String squadra2 = txSquadra2.getText();
        int gol1 = Integer.parseInt(txGol1.getText());
        int gol2 = Integer.parseInt(txGol2.getText());

        Partita partita = new Partita(giornata, squadra1, squadra2, gol1, gol2);
        boolean esiste = false;

        for (Partita partita1 : listapartite) {
            if (partita.equals(partita1)) {
                esiste = true;
            }
        }

        if (esiste == false) {
            listapartite.add(partita);
            JOptionPane.showMessageDialog(null, "PARTITA INSERITA CORRETTAMENTE!");
            clearPartite();
            salvaPartite();
        } else {
            JOptionPane.showMessageDialog(null, "NON È POSSIBILE INSERIRE UNA PARTITA GIÀ PRESENTE!");

        }
        refreshListaPartite();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnClassificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificaActionPerformed
        for (Squadra s : listasquadre) {
            int punteggio = s.getPunteggio();
            Classifica c = new Classifica(s.getNome(), punteggio);
            listaClassifica.add(c);

        }
        Collections.sort(listaClassifica);
        refreshListaClassifica();
    }//GEN-LAST:event_btnClassificaActionPerformed

    public void clear() {

        txNome.setText("");
        txSede.setText("");
    }

    public void clearPartite() {

        txGiornata.setText("");
        txSquadra1.setText("");
        txSquadra2.setText("");
        txGol1.setText("");
        txGol2.setText("");
    }

    private void refreshLista() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < listasquadre.size(); i++) {
            String nomesquadra = listasquadre.get(i).getNome();
            String sedesquadra = listasquadre.get(i).getSede();
            model.addElement(nomesquadra + " - " + sedesquadra);

        }
        ListSquadre.setModel(model);
    }

    private void refreshListaPartite() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < listapartite.size(); i++) {
            int giornata = listapartite.get(i).getGiornata();
            String squadra1 = listapartite.get(i).getSquadra1();
            String squadra2 = listapartite.get(i).getSquadra2();
            int gol1 = listapartite.get(i).getGol1();
            int gol2 = listapartite.get(i).getGol2();
            model.addElement(giornata + " - " + squadra1 + " - " + squadra2 + " - " + gol1 + " - " + gol2);

        }
        lstElencoPartite.setModel(model);
    }

    private void refreshListaClassifica() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < listaClassifica.size(); i++) {
            String nomesquadra = listaClassifica.get(i).nomesquadra;
            int punteggio = listaClassifica.get(i).punteggio;
            model.addElement(nomesquadra + " - " + punteggio);

        }
        lstClassifica.setModel(model);
    }

    public static void salvaSquadra() {
        String testoDisplay = "nome; sede; \n";
        for (int i = 0; i < listasquadre.size(); i++) {
            // recupero una squadra per volta
            Squadra squadra = listasquadre.get(i);
            String info = squadra.getCSV();
            testoDisplay = testoDisplay + info;
        }
        try {
            // creo file corsi.txt
            FileWriter myWriter = new FileWriter("/home/tss/Lucia/Java/TestEsame/src/it/tss/GestioneCalcio/Calcio.csv");
            //ci scrivo dentro testoDisplay
            myWriter.write(testoDisplay);
            // lo chiude se no si blocca
            myWriter.close();

        } catch (Exception e) {

        }
    }

    public static void salvaPartite() {
        String testoDisplay = "Giornata; squadra1; squadra2; gol1; gol2; \n";
        for (int i = 0; i < listapartite.size(); i++) {
            // recupero una partita per volta
            Partita partita = listapartite.get(i);
            String info = partita.getCSV();
            testoDisplay = testoDisplay + info;
        }
        try {
            // creo file corsi.txt
            FileWriter myWriter = new FileWriter("/home/tss/Lucia/Java/TestEsame/src/it/tss/GestioneCalcio/Partite.csv");
            //ci scrivo dentro testoDisplay
            myWriter.write(testoDisplay);
            // lo chiude se no si blocca
            myWriter.close();

        } catch (Exception e) {

        }
    }

    public void carica() {
        try {

            File filecsv = new File("/home/tss/Lucia/Java/TestEsame/src/it/tss/GestioneCalcio/Calcio.csv");
            //creo scanner per lelggere una riga per volta
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String[] dati = riga.split(";");

                    String nome = dati[0];
                    String sede = dati[1];

                    Squadra squadra = new Squadra(nome, sede);

                    listasquadre.add(squadra);

                }
                n++;
            }

            //la riga la taglio in tanti pezzi col ; in un array
            // elmento per lelemnto dell'array lo imposto ad un corso
            //il corso lo aggiungo alla lista 
            //e cosi' via per le altre righe del file'
            //alla fine chiudo il file se no si blocca
        } catch (Exception e) {

        }

    }

    public void caricaPartite() {
        try {

            File filecsv = new File("/home/tss/Lucia/Java/TestEsame/src/it/tss/GestioneCalcio/Partite.csv");
            //creo scanner per lelggere una riga per volta
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta
            int n = 1;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (n > 1) {
                    String[] dati = riga.split(";");

                    int giornata = Integer.parseInt(dati[0]);
                    String squadra1 = dati[1];
                    String squadra2 = dati[2];
                    int gol1 = Integer.parseInt(dati[3]);
                    int gol2 = Integer.parseInt(dati[4]);

                    Partita partita = new Partita(giornata, squadra1, squadra2, gol1, gol2);

                    listapartite.add(partita);

                }
                n++;
            }

            //la riga la taglio in tanti pezzi col ; in un array
            // elmento per lelemnto dell'array lo imposto ad un corso
            //il corso lo aggiungo alla lista 
            //e cosi' via per le altre righe del file'
            //alla fine chiudo il file se no si blocca
        } catch (Exception e) {

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinCalcio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListSquadre;
    private javax.swing.JButton btnClassifica;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNuovo;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClassifica;
    private javax.swing.JLabel lblGiornata;
    private javax.swing.JLabel lblGol1;
    private javax.swing.JLabel lblGol2;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPartita;
    private javax.swing.JLabel lblSede;
    private javax.swing.JLabel lblSquadra;
    private javax.swing.JLabel lblSquadra1;
    private javax.swing.JLabel lblSquadra2;
    private javax.swing.JLabel lblSquadre;
    private javax.swing.JList<String> lstClassifica;
    private javax.swing.JList<String> lstElencoPartite;
    private javax.swing.JTextField txGiornata;
    private javax.swing.JTextField txGol1;
    private javax.swing.JTextField txGol2;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txSede;
    private javax.swing.JTextField txSquadra1;
    private javax.swing.JTextField txSquadra2;
    // End of variables declaration//GEN-END:variables
}
